name: landify_design_flutter
description: "A Flutter web project implementing the Landify Landing Page UI Kit to explore and learn Flutter web development."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Thin.ttf
          weight: 100
        - asset: assets/font/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Inter-Light.ttf
          weight: 300
        - asset: assets/font/Inter-Regular.ttf
          weight: 400
        - asset: assets/font/Inter-Medium.ttf
          weight: 500
        - asset: assets/font/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/font/Inter-Bold.ttf
          weight: 700
        - asset: assets/font/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Inter-Black.ttf
          weight: 900